#!/bin/bash

ngx()
{
    nginx -p. -c`pwd`/nginx.conf $*
}

rule()
{
    case $1 in
        start)
            if [ -e nginx.pid ]; then
                echo "nginx is already started (or a stale nginx.pid is left over)."
                exit 1
            fi
            ngx
            ;;
        stop)
            ngx -s stop
            ;;
        *)
            echo "Unrecognized option: $1." >&2
            exit 1
            ;;
    esac
}

if [ $# -eq 0 ]; then
    rule start
else
    while [ $# -gt 0 ]; do
        rule $1
        shift
    done
fi
